export {default as Home} from "./home/Home"
export {default as Contact} from "./contact/Contact"
export {default as Login} from "./auth/Login"
export {default as Register} from "./auth/Register"
export {default as About} from "./about/About"
export {default as Products} from "./products/Products"
export {default as NewProducts} from "./newproducts/NewProducts"
export {default as Reset} from "./auth/Reset"
export {default as PopularProducts} from "./popularproducts/PopularProducts"
export {default as Admin} from "./admin/Admin"

